# Generated by Django 3.2.4 on 2021-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='actions',
            field=models.ManyToManyField(through='petsapi.Pet_Action', to='petsapi.Action'),
        ),
    ]
